version: '2.4'
services:
  db:
    image: postgres:alpine
    container_name: wdve-td-db-test
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    environment:
      - DATABASE_NAME=postgres-test
