version: '3'
services:
  db:
    image: postgres
    container_name: wdve-td-db
    ports:
      - "5432:5432"
  app:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    image: nodejs
    container_name: wdve-td-api
    depends_on:
      - db
    restart: always
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3000:3000"
    command: /usr/src/app/docker-entrypoint.sh
