version: '2.4'
services:
  db:
    image: postgres:alpine
    container_name: wdve-td-db
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  app:
    image: node:12.6.0-slim
    container_name: wdve-td-api
    command: /usr/src/app/server/docker-entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DIALECT: postgres
      DB_NAME: postgres
      DB_HOST: wdve-td-db
      DB_USERNAME: postgres
      DB_PASSWORD: null
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./server:/usr/src/app/server
    working_dir: /usr/src/app

