version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: postgres:alpine
        environment:
          POSTGRES_DB: postgres-test
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit test
          command: yarn test:unit
      - run:
          name: Integration test
          command: yarn test:integration
      - run:
          name: Push coverage to coveralls
          command: yarn coveralls
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
        
