version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  unit_test:
    docker:
      - image: circleci/node
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
        
