wdve-td:
  port: 3000
  limit: 5mb
  database:
    dialect: postgres
    host: 127.0.0.1
    database: postgres
    username: postgres
    password: null
  authentication:
    secret:
      cache: true
      rateLimit: true
      jwksRequestsPerMinute: 5
      jwksUri: __JWKS_URI__
    audience: __AUDIENCE__
    issuer: __ISSUER__
